apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hkd1w2lpc-dotnet-basic
  janus-idp.io/tekton: hkd1w2lpc-dotnet-basic
  backstage.io/kubernetes-id: hkd1w2lpc-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hkd1w2lpc-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
